alias grad="echoAndRun ./gradlew"
alias gradc="echoAndRun ./gradlew clean"
alias gradcb="echoAndRun ./gradlew clean build"
alias gradt="echoAndRun ./gradlew check"
alias gradr="echoAndRun ./gradlew run"
alias gradb="echoAndRun ./gradlew build"
alias gradbp="echoAndRun ./gradlew build --scan"