# Lazygit Configuration
# A simple terminal UI for git commands

gui:
  # Nord-inspired theme
  theme:
    activeBorderColor:
      - "#88c0d0" # Nord frost blue
      - bold
    inactiveBorderColor:
      - "#4c566a" # Nord dark gray
    selectedLineBgColor:
      - "#3b4252" # Nord darker gray (also applies to diff pane)

  # UI preferences
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: false
  showIcons: false

  # Skip confirmation dialogs (we're experienced users)
  skipDiscardChangeWarning: false
  skipStashWarning: false

git:
  # Use delta for beautiful diffs
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

  merging:
    manualCommit: false

  log:
    order: "topo-order"
    showGraph: "always"

  # Auto-fetch and refresh
  autoFetch: true
  autoRefresh: true

  # Branch commands
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"

  # Main branches
  mainBranches:
    - main
    - master

os:
  editPreset: "helix" # Use hx as editor

refresher:
  refreshInterval: 10
  fetchInterval: 60

update:
  method: never # Don't check for updates

confirmOnQuit: false
