format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$golang\
$rust\
$python\
$nodejs\
$package\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " 🔒"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( $conflicted$untracked$staged$renamed$deleted)](bright-black) ($modified$ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "!​"
untracked = "​"
modified = "*​"
staged = ""
renamed = "→​"
deleted = "x​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = " "
format = '[$symbol($version )(\($virtualenv\) )]($style)'
style = "bright-black"

[golang]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bright-black"

[rust]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bright-black"

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'
style = "bright-black"

[package]
symbol = " "
format = '[$symbol$version]($style) '
style = "bright-black"
disabled = false
